# Generated by Django 5.1.7 on 2025-04-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bookname', models.CharField(max_length=255)),
                ('bookpage', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('Okudum', 'Okudum'), ('Okuyorum', 'Okuyorum'), ('Okuyacağım', 'Okuyacağım')], max_length=20, null=True)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
